[[redirects]]
  from = "/api/*"
  to = "https://force-velocity-9211-dev-ed.scratch.my.salesforce-sites.com/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*", 
    Access-Control-Allow-Headers = "Content-Type, api_token", 
    Access-Control-Allow-Methods = "POST, OPTIONS"
  }
